---
title: "In-Class Template"
author: "Madeline Hulle"
format: pdf
---

# 1. Set Up

## Packages
```{r}
#| label: packages

# general use and cleaning

library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# wrap axis labels
library(scales)

# reading in .xlsx files
library(readxl)

# visualize mising data
library(naniar)

# arrange plots
library(patchwork)


```

## Data

```{r}
#| label: data

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

#survey data (reading different sheets in as seperate data frames)

aq_ins <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "Aquatic Insects")

# site information

sites <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "sites"
)

# water quaity

water_quality <- read_xlsx(
   here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
   sheet = "Water Quality",
   # values in df that are actually indicating missing values, making it seem as a chr when it should be num
   # different ways missing values show up in data set
   na = c("over", "", "n/a", "N/A", "173+")
)



```


# 2. Cleaning

## `sites` object

Goal: create a new object from `sites` that only includes NCOS sites

```{r}
#| label: cleaning-sites

# creating new oject from sites
ncos_sites <- sites |> 
  # filtering to only include NCOS quarterly sites
  filter(sector == "NCOS" & 
           sampling_frequency == "Quarterly")


```












